<<<<<<< HEAD
name: CI for FastAPI
=======
name: FastAPI CI
>>>>>>> a919ccd (CICD file)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
<<<<<<< HEAD
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
=======
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

>>>>>>> a919ccd (CICD file)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

<<<<<<< HEAD
      # Step 4: Run FastAPI app to test
=======
>>>>>>> a919ccd (CICD file)
      - name: Run FastAPI app and test
        run: |
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
          sleep 5
          curl -f http://127.0.0.1:8000 || exit 1
